# Generated by Django 4.0.2 on 2022-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('zilla', models.CharField(max_length=20)),
                ('upazilla', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
