# Generated by Django 4.0.2 on 2022-02-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_surveor_surveyor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('direct_answer', 'Direct Answer'), ('mcq_text', 'MCQ Text'), ('mcq_image', 'MCQ with Image'), ('mcq_others', 'MCQ Others'), ('boolean', 'Boolean')], max_length=20)),
                ('serial', models.CharField(max_length=11)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Survey_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyee_name', models.CharField(max_length=50)),
                ('surveyee_phone', models.CharField(max_length=15)),
                ('surveyee_address', models.CharField(max_length=100)),
                ('survey_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.survey')),
                ('surveyor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.surveyor')),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=500)),
                ('question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.question')),
                ('survey_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.survey_info')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.survey'),
        ),
        migrations.CreateModel(
            name='Available_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('post_question', models.BigIntegerField(default=-1)),
                ('question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.question')),
            ],
        ),
    ]
